### ISSUE TITLE
Add placemark triggers

### ISSUE THREAD

**Issue by bmr-cymru** [bmr-cymru/csv2kml#1]
Add the ability to trigger creation of a placemarker based on row data: for e.g. dropping a marker when the "return home" function is activated, or when battery levels are low.

**Comment by aseedig** [comment]
The field name for the return to home function is:
- flyCState

The following values are to be considered:
- AutoLanding
- AutoTakeoff
- GoHome
- GPS_Atti
- NaviGo

Additional statuses might be given later.

**Comment by bmr-cymru** [comment]
Added in commit 74f7182db7bd96d2bf0ac60ba51fa84c08cb6586:

```
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Sun Jan 14 20:16:56 2018 +0000

    csv2kml: add -s/--state-marks to write placemaker on state change
    
    Add a command line option to create a placemarker whenever the
    fly state changes. The name of the placemarker will be "old:new".
```
