### ISSUE TITLE
Place marks for Drone status change are default push-pin icons

### ISSUE THREAD

**Issue by aseedig** [bmr-cymru/csv2kml#7]
The custom icons for the drone status points on the map are replaced with the standard yellow push pins from google earth. 

I cannot see why this happened. If I compare 2 files from before adding the cone function, the format is almost the same.

This happens with any .csv file at the moment.

2 sample files for comparison attached.
[P4_M16_N1 BeforeCone.kml.txt](https://github.com/bmr-cymru/csv2kml/files/1804089/P4_M16_N1.BeforeCone.kml.txt)
[P4Pro_M16_N1 AfterCone.kml.txt](https://github.com/bmr-cymru/csv2kml/files/1804094/P4Pro_M16_N1.AfterCone.kml.txt)

**Comment by bmr-cymru** [comment]
Missing enclosing `<Style></Style>` tags. Fixed in 1486b88.
